### ISSUE TITLE
No example on how to use the directive?

### ISSUE THREAD

**Issue by sanyam-j** [ghinda/angular-meditor#7]

**Comment by ghinda** [comment]
You're right. I do need to improve the docs. 

In the meawhile take a look at the two demos demos (with inline content and ng-model) at:
https://ghinda.net/angular-meditor/

Here's how to use the directive:
https://github.com/ghinda/angular-meditor/blob/master/app/index.html#L46-L56

and
https://github.com/ghinda/angular-meditor/blob/master/app/index.html#L46-L56

This is the very basic angular module I'm using for the demo:
https://github.com/ghinda/angular-meditor/blob/master/app/scripts/demo.js

**Comment by sanyam-j** [comment]
Thanks for the links. Just want to know that can we load the google fonts in this?

**Comment by ghinda** [comment]
The fonts in the dropdown are loaded from Google Fonts, but there's no option to edit the list of fonts right now.

You can just copy the directive to your project, and edit the list of fonts in it. They'll get loaded from Google Fonts automatically.

This is the directive file:
https://github.com/ghinda/angular-meditor/blob/master/app/scripts/directives/editor.js

and this is the list of fonts you should edit:
https://github.com/ghinda/angular-meditor/blob/master/app/scripts/directives/editor.js#L68-L97

Make sure the font `label` is the one used by gfonts. 
This is where the directive dynamically loads a font when it's selected: 
https://github.com/ghinda/angular-meditor/blob/master/app/scripts/directives/editor.js#L293-L297

**Comment by sanyam-j** [comment]
@ghinda  Sure i will do that. I need the text alignment and color change too. How can i do that?

**Comment by ghinda** [comment]
You'll have to add extra menus for those, and create the functionality yourself. 

See how `execCommand` is used and the possible commands here:
https://developer.mozilla.org/en-US/docs/Web/API/document/execCommand#Commands
